<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../CBS.BI.Application/CBS.BI.Application.csproj" />
    <ProjectReference Include="../../CBS.BI.Infrastructure/CBS.BI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
